# ✈️ Airline Flight Delay Intelligence & Operational Performance Analytics

## 1. Project Overview

This project analyzes a large-scale airline flight dataset containing
3 million flight records and 32 variables.

The purpose of the project is to understand airline operational
performance, identify delay patterns, analyze airports and routes,
investigate major delay causes, and generate actionable business insights.

The project follows an end-to-end Data Analytics workflow using:

- Python
- NumPy
- Pandas
- Matplotlib
- Seaborn
- MySQL
- Tableau

Machine Learning and Artificial Intelligence are outside the scope
of this project.

## Final Objective

Transform raw airline operational data into:

- Reliable KPIs
- Airline performance benchmarks
- Airport and route intelligence
- Delay root-cause analysis
- Rule-based operational scoring
- SQL analytical reports
- Tableau dashboards
- Business recommendations

## 2. Business Problem

Flight delays, cancellations, and diversions can negatively affect
airline operations, customer experience, scheduling, and resource planning.

Management needs a clear view of where operational problems occur
and which areas should receive priority.

This project will investigate:

1. Which airlines have better or worse operational performance?
2. Which airports experience higher delay exposure?
3. Which routes have higher operational risk?
4. What are the major causes of delays?
5. How often are flights cancelled or diverted?
6. How does operational performance change over time?
7. Which airlines, airports, and routes require management attention?
8. What actions can be recommended from the analysis?

## 3. Dataset Scope

The dataset represents individual flight records.

Important business dimensions include:

- Date
- Airline
- Flight number
- Origin airport
- Destination airport
- Scheduled departure
- Actual departure
- Departure delay
- Scheduled arrival
- Actual arrival
- Arrival delay
- Cancellation
- Diversion
- Flight duration
- Air time
- Distance
- Delay causes

The dataset contains 3,000,000 records and 32 variables.

# Phase 1 — Python Fundamentals for Data Analytics

This phase builds the Python foundation required for the project.

Topics covered:

- Python fundamentals
- Variables
- Data types
- Operators
- Conditions
- Data-driven problem solving

Every concept is applied to the airline dataset rather than using
unrelated practice data.

In [1]:
# Import the core Python libraries

import pandas as pd
import numpy as np
import os

## 4. Data Ingestion

The complete airline dataset is loaded into a Pandas DataFrame.

The variable `df` will remain the main source DataFrame throughout
the project.

In [2]:
# Define the absolute source dataset path
file_path = r"F:\Data science\intern all file\project\Airlines project final intern\data\raw_data\flight_delay.csv"

# Load the complete dataset
df = pd.read_csv(file_path)
df.shape

(3000000, 32)

In [3]:
df

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2022-11-13,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1522,JAX,"Jacksonville, FL",CLT,"Charlotte, NC",...,0.0,85.0,71.0,55.0,328.0,NaN,NaN,NaN,NaN,NaN
2999996,2022-11-02,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1535,ORD,"Chicago, IL",AUS,"Austin, TX",...,0.0,176.0,145.0,130.0,977.0,NaN,NaN,NaN,NaN,NaN
2999997,2022-09-11,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2745,HSV,"Huntsville, AL",ATL,"Atlanta, GA",...,0.0,55.0,50.0,28.0,151.0,0.0,36.0,0.0,0.0,0.0
2999998,2019-11-13,Republic Airline,Republic Airline: YX,YX,20452,6134,BOS,"Boston, MA",LGA,"New York, NY",...,0.0,88.0,77.0,50.0,184.0,NaN,NaN,NaN,NaN,NaN
2999999,2019-06-15,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,2823,LGB,"Long Beach, CA",SJC,"San Jose, CA",...,0.0,70.0,63.0,52.0,324.0,NaN,NaN,NaN,NaN,NaN

## 5. Initial Data Inspection

The raw dataset is inspected before any transformation.

The purpose is to understand the original data structure and
establish a baseline for later cleaning and analysis.

In [4]:
# Preview the first five flight records

df.head()

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Preview the last five flight records

df.tail()

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
2999995,2022-11-13,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1522,JAX,"Jacksonville, FL",CLT,"Charlotte, NC",...,0.0,85.0,71.0,55.0,328.0,NaN,NaN,NaN,NaN,NaN
2999996,2022-11-02,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1535,ORD,"Chicago, IL",AUS,"Austin, TX",...,0.0,176.0,145.0,130.0,977.0,NaN,NaN,NaN,NaN,NaN
2999997,2022-09-11,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2745,HSV,"Huntsville, AL",ATL,"Atlanta, GA",...,0.0,55.0,50.0,28.0,151.0,0.0,36.0,0.0,0.0,0.0
2999998,2019-11-13,Republic Airline,Republic Airline: YX,YX,20452,6134,BOS,"Boston, MA",LGA,"New York, NY",...,0.0,88.0,77.0,50.0,184.0,NaN,NaN,NaN,NaN,NaN
2999999,2019-06-15,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,2823,LGB,"Long Beach, CA",SJC,"San Jose, CA",...,0.0,70.0,63.0,52.0,324.0,NaN,NaN,NaN,NaN,NaN

## 6. Dataset Dimensions

Python variables are used to store the number of records
and variables in the dataset.

These variables will later support project-level KPI calculations.

In [6]:
# Store dataset dimensions

total_flights = df.shape[0]
total_variables = df.shape[1]

total_flights, total_variables

(3000000, 32)

## 7. Variable and Column Inventory

The available columns are reviewed to understand which variables
belong to airline, route, scheduling, operational, cancellation,
and delay categories.

In [7]:
# Store all column names in a Python list

column_names = df.columns.tolist()

column_names

['FL_DATE',
 'AIRLINE',
 'AIRLINE_DOT',
 'AIRLINE_CODE',
 'DOT_CODE',
 'FL_NUMBER',
 'ORIGIN',
 'ORIGIN_CITY',
 'DEST',
 'DEST_CITY',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'WHEELS_ON',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'DELAY_DUE_CARRIER',
 'DELAY_DUE_WEATHER',
 'DELAY_DUE_NAS',
 'DELAY_DUE_SECURITY',
 'DELAY_DUE_LATE_AIRCRAFT']

## 8. Data Types

Data types determine how variables should be processed.

Dates may require datetime conversion.
Categorical fields can be grouped and segmented.
Numerical fields can be used for calculations and statistical analysis.

In [8]:
# Inspect data types of all columns

df.dtypes

FL_DATE                        str
AIRLINE                        str
AIRLINE_DOT                    str
AIRLINE_CODE                   str
DOT_CODE                     int64
FL_NUMBER                    int64
ORIGIN                         str
ORIGIN_CITY                    str
DEST                           str
DEST_CITY                      str
CRS_DEP_TIME                 int64
DEP_TIME                   float64
DEP_DELAY                  float64
TAXI_OUT                   float64
WHEELS_OFF                 float64
WHEELS_ON                  float64
TAXI_IN                    float64
CRS_ARR_TIME                 int64
ARR_TIME                   float64
ARR_DELAY                  float64
CANCELLED                  float64
CANCELLATION_CODE              str
DIVERTED                   float64
CRS_ELAPSED_TIME           float64
ELAPSED_TIME               float64
AIR_TIME                   float64
DISTANCE                   float64
DELAY_DUE_CARRIER          float64
DELAY_DUE_WEATHER          float64
DELAY_DUE_NAS              float64
DELAY_DUE_SECURITY         float64
DELAY_DUE_LATE_AIRCRAFT    float64
dtype: object

## 9. Missing Value Audit

Missing values are measured before cleaning.

A missing value is not automatically an error.

For example, operational fields may be missing because a flight
was cancelled or because an operational event did not occur.

The cleaning stage will therefore use business logic rather than
blindly replacing all missing values.

In [9]:
# Calculate missing values and percentages

missing_count = df.isna().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

missing_report = (
    missing_report[
        missing_report["Missing_Count"] > 0
    ]
    .sort_values(
        "Missing_Percentage",
        ascending=False
    )
)

missing_report

                         Missing_Count  Missing_Percentage
CANCELLATION_CODE              2920860           97.362000
DELAY_DUE_WEATHER              2466137           82.204567
DELAY_DUE_NAS                  2466137           82.204567
DELAY_DUE_SECURITY             2466137           82.204567
DELAY_DUE_LATE_AIRCRAFT        2466137           82.204567
DELAY_DUE_CARRIER              2466137           82.204567
AIR_TIME                         86198            2.873267
ELAPSED_TIME                     86198            2.873267
ARR_DELAY                        86198            2.873267
TAXI_IN                          79944            2.664800
WHEELS_ON                        79944            2.664800
ARR_TIME                         79942            2.664733
TAXI_OUT                         78806            2.626867
WHEELS_OFF                       78806            2.626867
DEP_DELAY                        77644            2.588133
DEP_TIME                         77615            2.587167
CRS_ELAPSED_TIME                    14            0.000467

## 10. Duplicate Audit

Exact duplicate rows are identified before any cleaning decision.

The number of duplicate records will be documented and evaluated
before removing anything.

In [10]:
# Count exact duplicate records

duplicate_count = df.duplicated().sum()

duplicate_count

np.int64(0)

## 11. Core Operational Variables

The following variables represent important operational measures:

- DEP_DELAY — departure delay
- ARR_DELAY — arrival delay
- CANCELLED — cancellation indicator
- DIVERTED — diversion indicator
- DISTANCE — flight distance

These variables will form the foundation of later KPI and
performance analysis.

In [11]:
# Define the main operational variables

operational_columns = [
    "DEP_DELAY",
    "ARR_DELAY",
    "CANCELLED",
    "DIVERTED",
    "DISTANCE"
]

operational_columns

['DEP_DELAY', 'ARR_DELAY', 'CANCELLED', 'DIVERTED', 'DISTANCE']

## 12. Python Variables and Operators in a Business Context

Variables are used to calculate initial operational indicators.

These values will later be compared with airline-level,
airport-level, route-level, and time-based metrics.

In [12]:
# Calculate initial operational KPIs

total_flights = len(df)

total_airlines = df["AIRLINE"].nunique()

average_departure_delay = df["DEP_DELAY"].mean()

average_arrival_delay = df["ARR_DELAY"].mean()

total_cancelled = df["CANCELLED"].sum()

total_diverted = df["DIVERTED"].sum()

(
    total_flights,
    total_airlines,
    average_departure_delay,
    average_arrival_delay,
    total_cancelled,
    total_diverted
)

(3000000,
 18,
 np.float64(10.123326179288219),
 np.float64(4.260858150279257),
 np.float64(79140.0),
 np.float64(7056.0))

## 13. Conditional Logic for Operational Status

Conditional statements are used to convert a numerical KPI into
a business-friendly operational classification.

This is the beginning of the project's rule-based analytical logic.

The rule is based on average arrival delay:

- 0 or below: On Time / Early
- Above 0 to 5: Low Delay
- Above 5 to 15: Moderate Delay
- Above 15: High Delay

In [13]:
# Classify overall arrival-delay performance

if average_arrival_delay <= 0:
    operational_status = "On Time / Early"

elif average_arrival_delay <= 5:
    operational_status = "Low Delay"

elif average_arrival_delay <= 15:
    operational_status = "Moderate Delay"

else:
    operational_status = "High Delay"

operational_status

'Low Delay'

## 14. Phase 1 Validation

Before moving to the next phase, the following foundation has been
established:

- Dataset loaded successfully
- Dataset dimensions verified
- Columns identified
- Data types assessed
- Missing values audited
- Duplicate records audited
- Operational variables identified
- Basic KPIs calculated
- Conditional business classification implemented

The next stage will apply Python loops, lists, and practical
problem-solving to the airline dataset.

# Phase 2 — Python Loops and Lists

In this phase, Python loops and lists will be applied to the airline
dataset.

The objective is not only to learn syntax, but to solve practical
data-analysis problems using the actual project data.

Topics covered:

- Lists
- List operations
- for loops
- Conditional logic inside loops
- Practical business calculations
- Building reusable analytical structures

In [14]:
# Create a list of important airline analysis columns

analysis_columns = [
    "AIRLINE",
    "ORIGIN",
    "DEST",
    "DEP_DELAY",
    "ARR_DELAY",
    "CANCELLED",
    "DIVERTED",
    "DISTANCE"
]

analysis_columns

['AIRLINE',
 'ORIGIN',
 'DEST',
 'DEP_DELAY',
 'ARR_DELAY',
 'CANCELLED',
 'DIVERTED',
 'DISTANCE']

## 2.1 Airline List

The airline column contains the airline names operating in the dataset.

A unique list is created to support airline-level analysis.

In [15]:
# Create a unique list of airlines

airlines = (
    df["AIRLINE"]
    .dropna()
    .unique()
    .tolist()
)

len(airlines), airlines

(18,
 ['United Air Lines Inc.',
  'Delta Air Lines Inc.',
  'Spirit Air Lines',
  'Southwest Airlines Co.',
  'American Airlines Inc.',
  'Republic Airline',
  'Alaska Airlines Inc.',
  'JetBlue Airways',
  'PSA Airlines Inc.',
  'Allegiant Air',
  'ExpressJet Airlines LLC d/b/a aha!',
  'SkyWest Airlines Inc.',
  'Endeavor Air Inc.',
  'Envoy Air',
  'Frontier Airlines Inc.',
  'Mesa Airlines Inc.',
  'Horizon Air',
  'Hawaiian Airlines Inc.'])

## 2.2 Loop Through Airlines

A for-loop is used to process each airline individually.

This approach demonstrates how a programming loop can be used to
perform repeated business analysis across multiple airline groups.

In [16]:
# Display each airline using a loop

for airline in airlines:
    print(airline)

United Air Lines Inc.
Delta Air Lines Inc.
Spirit Air Lines
Southwest Airlines Co.
American Airlines Inc.
Republic Airline
Alaska Airlines Inc.
JetBlue Airways
PSA Airlines Inc.
Allegiant Air
ExpressJet Airlines LLC d/b/a aha!
SkyWest Airlines Inc.
Endeavor Air Inc.
Envoy Air
Frontier Airlines Inc.
Mesa Airlines Inc.
Horizon Air
Hawaiian Airlines Inc.

## 2.3 Count Flights for Each Airline

The loop is extended to calculate the number of flights operated
by each airline.

This provides a basic operational-volume comparison.

In [17]:
# Calculate flight volume for every airline

airline_flight_counts = []

for airline in airlines:
    
    flight_count = len(
        df[df["AIRLINE"] == airline]
    )
    
    airline_flight_counts.append(
        (airline, flight_count)
    )

airline_flight_counts

[('United Air Lines Inc.', 254504),
 ('Delta Air Lines Inc.', 395239),
 ('Spirit Air Lines', 95711),
 ('Southwest Airlines Co.', 576470),
 ('American Airlines Inc.', 383106),
 ('Republic Airline', 143107),
 ('Alaska Airlines Inc.', 100467),
 ('JetBlue Airways', 112844),
 ('PSA Airlines Inc.', 107050),
 ('Allegiant Air', 52738),
 ('ExpressJet Airlines LLC d/b/a aha!', 19082),
 ('SkyWest Airlines Inc.', 343737),
 ('Endeavor Air Inc.', 112463),
 ('Envoy Air', 121256),
 ('Frontier Airlines Inc.', 64466),
 ('Mesa Airlines Inc.', 65012),
 ('Horizon Air', 20634),
 ('Hawaiian Airlines Inc.', 32114)]

## 2.4 Identify the Largest Airline by Flight Volume

The maximum flight count is identified using Python's built-in
max() function.

This demonstrates combining lists, tuples, and functions to answer
a practical business question.

In [18]:
# Find the airline operating the highest number of flights

largest_airline = max(
    airline_flight_counts,
    key=lambda x: x[1]
)

largest_airline

('Southwest Airlines Co.', 576470)

## 2.5 Identify the Smallest Airline by Flight Volume

The same analytical structure can be used to identify the airline
with the lowest number of flights.

This demonstrates how reusable Python logic can answer different
business questions.

In [19]:
# Find the airline with the lowest flight volume

smallest_airline = min(
    airline_flight_counts,
    key=lambda x: x[1]
)

smallest_airline

('ExpressJet Airlines LLC d/b/a aha!', 19082)

## 2.6 Sort Airline Flight Volumes

The airline-level results are sorted from highest to lowest
flight volume.

Sorting is useful for ranking airlines and preparing management
reports.

In [20]:
# Sort airlines by number of flights

airline_volume_sorted = sorted(
    airline_flight_counts,
    key=lambda x: x[1],
    reverse=True
)

airline_volume_sorted

[('Southwest Airlines Co.', 576470),
 ('Delta Air Lines Inc.', 395239),
 ('American Airlines Inc.', 383106),
 ('SkyWest Airlines Inc.', 343737),
 ('United Air Lines Inc.', 254504),
 ('Republic Airline', 143107),
 ('Envoy Air', 121256),
 ('JetBlue Airways', 112844),
 ('Endeavor Air Inc.', 112463),
 ('PSA Airlines Inc.', 107050),
 ('Alaska Airlines Inc.', 100467),
 ('Spirit Air Lines', 95711),
 ('Mesa Airlines Inc.', 65012),
 ('Frontier Airlines Inc.', 64466),
 ('Allegiant Air', 52738),
 ('Hawaiian Airlines Inc.', 32114),
 ('Horizon Air', 20634),
 ('ExpressJet Airlines LLC d/b/a aha!', 19082)]

## 2.7 Convert Airline Results into a Dictionary

A dictionary is useful when a business metric needs to be accessed
directly using a key.

Here, the airline name becomes the key and flight volume becomes
the value.

In [21]:
# Create an airline-to-flight-volume dictionary

airline_flight_dict = dict(
    airline_volume_sorted
)

airline_flight_dict

{'Southwest Airlines Co.': 576470,
 'Delta Air Lines Inc.': 395239,
 'American Airlines Inc.': 383106,
 'SkyWest Airlines Inc.': 343737,
 'United Air Lines Inc.': 254504,
 'Republic Airline': 143107,
 'Envoy Air': 121256,
 'JetBlue Airways': 112844,
 'Endeavor Air Inc.': 112463,
 'PSA Airlines Inc.': 107050,
 'Alaska Airlines Inc.': 100467,
 'Spirit Air Lines': 95711,
 'Mesa Airlines Inc.': 65012,
 'Frontier Airlines Inc.': 64466,
 'Allegiant Air': 52738,
 'Hawaiian Airlines Inc.': 32114,
 'Horizon Air': 20634,
 'ExpressJet Airlines LLC d/b/a aha!': 19082}

## 2.8 Build Airline-Level Operational Metrics

Multiple operational metrics are calculated for every airline.

These metrics will become the foundation for the project's
airline performance benchmarking.

Metrics include:

- Total flights
- Average departure delay
- Average arrival delay
- Cancelled flights
- Diverted flights

In [22]:
# Build airline-level operational metrics

airline_analysis = []

for airline in airlines:

    airline_data = df[
        df["AIRLINE"] == airline
    ]

    airline_analysis.append({
        "AIRLINE": airline,
        "TOTAL_FLIGHTS": len(airline_data),
        "AVERAGE_DEP_DELAY": airline_data["DEP_DELAY"].mean(),
        "AVERAGE_ARR_DELAY": airline_data["ARR_DELAY"].mean(),
        "CANCELLED_FLIGHTS": airline_data["CANCELLED"].sum(),
        "DIVERTED_FLIGHTS": airline_data["DIVERTED"].sum()
    })

airline_analysis

[{'AIRLINE': 'United Air Lines Inc.',
  'TOTAL_FLIGHTS': 254504,
  'AVERAGE_DEP_DELAY': np.float64(11.217032073646134),
  'AVERAGE_ARR_DELAY': np.float64(5.035985016312885),
  'CANCELLED_FLIGHTS': np.float64(5536.0),
  'DIVERTED_FLIGHTS': np.float64(698.0)},
 {'AIRLINE': 'Delta Air Lines Inc.',
  'TOTAL_FLIGHTS': 395239,
  'AVERAGE_DEP_DELAY': np.float64(8.106747590146377),
  'AVERAGE_ARR_DELAY': np.float64(1.0850788339017954),
  'CANCELLED_FLIGHTS': np.float64(5982.0),
  'DIVERTED_FLIGHTS': np.float64(782.0)},
 {'AIRLINE': 'Spirit Air Lines',
  'TOTAL_FLIGHTS': 95711,
  'AVERAGE_DEP_DELAY': np.float64(12.981880063789026),
  'AVERAGE_ARR_DELAY': np.float64(8.029484978540772),
  'CANCELLED_FLIGHTS': np.float64(2312.0),
  'DIVERTED_FLIGHTS': np.float64(199.0)},
 {'AIRLINE': 'Southwest Airlines Co.',
  'TOTAL_FLIGHTS': 576470,
  'AVERAGE_DEP_DELAY': np.float64(10.81695730607336),
  'AVERAGE_ARR_DELAY': np.float64(3.2697955813330117),
  'CANCELLED_FLIGHTS': np.float64(19465.0),
  'DIVERTED_FLIGHTS': np.float64(1136.0)},
 {'AIRLINE': 'American Airlines Inc.',
  'TOTAL_FLIGHTS': 383106,
  'AVERAGE_DEP_DELAY': np.float64(12.609895258577868),
  'AVERAGE_ARR_DELAY': np.float64(6.661228711969786),
  'CANCELLED_FLIGHTS': np.float64(10907.0),
  'DIVERTED_FLIGHTS': np.float64(981.0)},
 {'AIRLINE': 'Republic Airline',
  'TOTAL_FLIGHTS': 143107,
  'AVERAGE_DEP_DELAY': np.float64(5.8043589614099895),
  'AVERAGE_ARR_DELAY': np.float64(0.5901756824252427),
  'CANCELLED_FLIGHTS': np.float64(4646.0),
  'DIVERTED_FLIGHTS': np.float64(313.0)},
 {'AIRLINE': 'Alaska Airlines Inc.',
  'TOTAL_FLIGHTS': 100467,
  'AVERAGE_DEP_DELAY': np.float64(4.640017847002515),
  'AVERAGE_ARR_DELAY': np.float64(1.0979001770199606),
  'CANCELLED_FLIGHTS': np.float64(1934.0),
  'DIVERTED_FLIGHTS': np.float64(239.0)},
 {'AIRLINE': 'JetBlue Airways',
  'TOTAL_FLIGHTS': 112844,
  'AVERAGE_DEP_DELAY': np.float64(18.322555104566717),
  'AVERAGE_ARR_DELAY': np.float64(12.276124516889453),
  'CANCELLED_FLIGHTS': np.float64(3039.0),
  'DIVERTED_FLIGHTS': np.float64(358.0)},
 {'AIRLINE': 'PSA Airlines Inc.',
  'TOTAL_FLIGHTS': 107050,
  'AVERAGE_DEP_DELAY': np.float64(7.972124328384077),
  'AVERAGE_ARR_DELAY': np.float64(3.9286549481557356),
  'CANCELLED_FLIGHTS': np.float64(3301.0),
  'DIVERTED_FLIGHTS': np.float64(266.0)},
 {'AIRLINE': 'Allegiant Air',
  'TOTAL_FLIGHTS': 52738,
  'AVERAGE_DEP_DELAY': np.float64(13.907796771695754),
  'AVERAGE_ARR_DELAY': np.float64(13.284601127961896),
  'CANCELLED_FLIGHTS': np.float64(2383.0),
  'DIVERTED_FLIGHTS': np.float64(176.0)},
 {'AIRLINE': 'ExpressJet Airlines LLC d/b/a aha!',
  'TOTAL_FLIGHTS': 19082,
  'AVERAGE_DEP_DELAY': np.float64(12.774461948080763),
  'AVERAGE_ARR_DELAY': np.float64(10.03197593448833),
  'CANCELLED_FLIGHTS': np.float64(1062.0),
  'DIVERTED_FLIGHTS': np.float64(69.0)},
 {'AIRLINE': 'SkyWest Airlines Inc.',
  'TOTAL_FLIGHTS': 343737,
  'AVERAGE_DEP_DELAY': np.float64(9.458294288612626),
  'AVERAGE_ARR_DELAY': np.float64(4.023311421969874),
  'CANCELLED_FLIGHTS': np.float64(7745.0),
  'DIVERTED_FLIGHTS': np.float64(1006.0)},
 {'AIRLINE': 'Endeavor Air Inc.',
  'TOTAL_FLIGHTS': 112463,
  'AVERAGE_DEP_DELAY': np.float64(5.951134919193754),
  'AVERAGE_ARR_DELAY': np.float64(-1.2585390721724565),
  'CANCELLED_FLIGHTS': np.float64(2394.0),
  'DIVERTED_FLIGHTS': np.float64(221.0)},
 {'AIRLINE': 'Envoy Air',
  'TOTAL_FLIGHTS': 121256,
  'AVERAGE_DEP_DELAY': np.float64(6.728256254352146),
  'AVERAGE_ARR_DELAY': np.float64(3.2789143480632843),
  'CANCELLED_FLIGHTS': np.float64(3633.0),
  'DIVERTED_FLIGHTS': np.float64(311.0)},
 {'AIRLINE': 'Frontier Airlines Inc.',
  'TOTAL_FLIGHTS': 64466,
  'AVERAGE_DEP_DELAY': np.float64(16.03357413359641),
  'AVERAGE_ARR_DELAY': np.float64(11.100428951858525),
  'CANCELLED_FLIGHTS': np.float64(1666.0),
  'DIVERTED_FLIGHTS': np.float64(88.0)},
 {'AIRLINE': 'Mesa Airlines Inc.',
  'TOTAL_FLIGHTS': 65012,
  'AVERAGE_DEP_DELAY': np.float64(12.277382509651277),
  'AVERAGE_ARR_DELAY': np.float64(7.3098100100837105),
  'CANCELLED_FLIGHTS': np.float64(2373.0),
  'DIVERTED_FLIGHTS': np.float64(162.0)},
 {'AIRLINE': 'Horizon Air',
  'TOTAL_FLIGHTS': 20634,
  'AVERAGE_DEP_DELAY': np.float64(4.832774600670479),
  'AVERAGE_ARR_DELAY': np.float64(2.3762415377773385),
  'CANCELLED_FLIGHTS': np.float64(374.0),
  'DIVERTED_FLIGHTS': np.float64(23.0)},
 {'AIRLINE': 'Hawaiian Airlines Inc.',
  'TOTAL_FLIGHTS': 32114,
  'AVERAGE_DEP_DELAY': np.float64(5.089536716041601),
  'AVERAGE_ARR_DELAY': np.float64(3.8947567669884537),
  'CANCELLED_FLIGHTS': np.float64(388.0),
  'DIVERTED_FLIGHTS': np.float64(28.0)}]

## 2.9 Convert Airline Analysis into a DataFrame

The list of airline-level dictionaries is converted into a Pandas
DataFrame.

This allows the results to be sorted, filtered, compared, and
extended with additional analytical metrics.

In [23]:
# Convert airline analysis into a DataFrame

airline_summary = pd.DataFrame(
    airline_analysis
)

airline_summary

,AIRLINE,TOTAL_FLIGHTS,AVERAGE_DEP_DELAY,AVERAGE_ARR_DELAY,CANCELLED_FLIGHTS,DIVERTED_FLIGHTS
0,United Air Lines Inc.,254504,11.217032,5.035985,5536.0,698.0
1,Delta Air Lines Inc.,395239,8.106748,1.085079,5982.0,782.0
2,Spirit Air Lines,95711,12.981880,8.029485,2312.0,199.0
3,Southwest Airlines Co.,576470,10.816957,3.269796,19465.0,1136.0
4,American Airlines Inc.,383106,12.609895,6.661229,10907.0,981.0
5,Republic Airline,143107,5.804359,0.590176,4646.0,313.0
6,Alaska Airlines Inc.,100467,4.640018,1.097900,1934.0,239.0
7,JetBlue Airways,112844,18.322555,12.276125,3039.0,358.0
8,PSA Airlines Inc.,107050,7.972124,3.928655,3301.0,266.0
9,Allegiant Air,52738,13.907797,13.284601,2383.0,176.0
10,ExpressJet Airlines LLC d/b/a aha!,19082,12.774462,10.031976,1062.0,69.0
11,SkyWest Airlines Inc.,343737,9.458294,4.023311,7745.0,1006.0
12,Endeavor Air Inc.,112463,5.951135,-1.258539,2394.0,221.0
13,Envoy Air,121256,6.728256,3.278914,3633.0,311.0
14,Frontier Airlines Inc.,64466,16.033574,11.100429,1666.0,88.0
15,Mesa Airlines Inc.,65012,12.277383,7.309810,2373.0,162.0
16,Horizon Air,20634,4.832775,2.376242,374.0,23.0
17,Hawaiian Airlines Inc.,32114,5.089537,3.894757,388.0,28.0

## 2.10 Calculate Cancellation and Diversion Rates

Absolute cancellation and diversion counts are not sufficient for
fair comparison because airlines operate different numbers of flights.

Rates are therefore calculated relative to total flight volume.

In [24]:
# Calculate cancellation and diversion rates

airline_summary["CANCELLATION_RATE"] = (
    airline_summary["CANCELLED_FLIGHTS"]
    / airline_summary["TOTAL_FLIGHTS"]
) * 100

airline_summary["DIVERSION_RATE"] = (
    airline_summary["DIVERTED_FLIGHTS"]
    / airline_summary["TOTAL_FLIGHTS"]
) * 100

airline_summary

,AIRLINE,TOTAL_FLIGHTS,AVERAGE_DEP_DELAY,AVERAGE_ARR_DELAY,CANCELLED_FLIGHTS,DIVERTED_FLIGHTS,CANCELLATION_RATE,DIVERSION_RATE
0,United Air Lines Inc.,254504,11.217032,5.035985,5536.0,698.0,2.175211,0.274259
1,Delta Air Lines Inc.,395239,8.106748,1.085079,5982.0,782.0,1.513515,0.197855
2,Spirit Air Lines,95711,12.981880,8.029485,2312.0,199.0,2.415605,0.207918
3,Southwest Airlines Co.,576470,10.816957,3.269796,19465.0,1136.0,3.376585,0.197061
4,American Airlines Inc.,383106,12.609895,6.661229,10907.0,981.0,2.846993,0.256065
5,Republic Airline,143107,5.804359,0.590176,4646.0,313.0,3.246522,0.218717
6,Alaska Airlines Inc.,100467,4.640018,1.097900,1934.0,239.0,1.925010,0.237889
7,JetBlue Airways,112844,18.322555,12.276125,3039.0,358.0,2.693098,0.317252
8,PSA Airlines Inc.,107050,7.972124,3.928655,3301.0,266.0,3.083606,0.248482
9,Allegiant Air,52738,13.907797,13.284601,2383.0,176.0,4.518563,0.333725
10,ExpressJet Airlines LLC d/b/a aha!,19082,12.774462,10.031976,1062.0,69.0,5.565454,0.361597
11,SkyWest Airlines Inc.,343737,9.458294,4.023311,7745.0,1006.0,2.253176,0.292666
12,Endeavor Air Inc.,112463,5.951135,-1.258539,2394.0,221.0,2.128700,0.196509
13,Envoy Air,121256,6.728256,3.278914,3633.0,311.0,2.996140,0.256482
14,Frontier Airlines Inc.,64466,16.033574,11.100429,1666.0,88.0,2.584308,0.136506
15,Mesa Airlines Inc.,65012,12.277383,7.309810,2373.0,162.0,3.650095,0.249185
16,Horizon Air,20634,4.832775,2.376242,374.0,23.0,1.812542,0.111467
17,Hawaiian Airlines Inc.,32114,5.089537,3.894757,388.0,28.0,1.208196,0.087189

## 2.11 Airline Performance Ranking

Airlines are ranked according to average arrival delay.

A lower average arrival delay represents better delay performance.

This is a descriptive ranking only. A multi-factor operational
scoring algorithm will be developed later after data cleaning and
validation.

In [25]:
# Rank airlines by average arrival delay

airline_performance_ranking = (
    airline_summary
    .sort_values(
        "AVERAGE_ARR_DELAY",
        ascending=True
    )
    .reset_index(drop=True)
)

airline_performance_ranking

,AIRLINE,TOTAL_FLIGHTS,AVERAGE_DEP_DELAY,AVERAGE_ARR_DELAY,CANCELLED_FLIGHTS,DIVERTED_FLIGHTS,CANCELLATION_RATE,DIVERSION_RATE
0,Endeavor Air Inc.,112463,5.951135,-1.258539,2394.0,221.0,2.128700,0.196509
1,Republic Airline,143107,5.804359,0.590176,4646.0,313.0,3.246522,0.218717
2,Delta Air Lines Inc.,395239,8.106748,1.085079,5982.0,782.0,1.513515,0.197855
3,Alaska Airlines Inc.,100467,4.640018,1.097900,1934.0,239.0,1.925010,0.237889
4,Horizon Air,20634,4.832775,2.376242,374.0,23.0,1.812542,0.111467
5,Southwest Airlines Co.,576470,10.816957,3.269796,19465.0,1136.0,3.376585,0.197061
6,Envoy Air,121256,6.728256,3.278914,3633.0,311.0,2.996140,0.256482
7,Hawaiian Airlines Inc.,32114,5.089537,3.894757,388.0,28.0,1.208196,0.087189
8,PSA Airlines Inc.,107050,7.972124,3.928655,3301.0,266.0,3.083606,0.248482
9,SkyWest Airlines Inc.,343737,9.458294,4.023311,7745.0,1006.0,2.253176,0.292666
10,United Air Lines Inc.,254504,11.217032,5.035985,5536.0,698.0,2.175211,0.274259
11,American Airlines Inc.,383106,12.609895,6.661229,10907.0,981.0,2.846993,0.256065
12,Mesa Airlines Inc.,65012,12.277383,7.309810,2373.0,162.0,3.650095,0.249185
13,Spirit Air Lines,95711,12.981880,8.029485,2312.0,199.0,2.415605,0.207918
14,ExpressJet Airlines LLC d/b/a aha!,19082,12.774462,10.031976,1062.0,69.0,5.565454,0.361597
15,Frontier Airlines Inc.,64466,16.033574,11.100429,1666.0,88.0,2.584308,0.136506
16,JetBlue Airways,112844,18.322555,12.276125,3039.0,358.0,2.693098,0.317252
17,Allegiant Air,52738,13.907797,13.284601,2383.0,176.0,4.518563,0.333725

## 2.12 Identify the Best and Worst Average Arrival Performance

The airline with the lowest average arrival delay and the airline
with the highest average arrival delay are identified.

These results are preliminary because the final project ranking
will be produced after the cleaning process.

In [26]:
# Identify best and worst average arrival-delay performance

best_arrival_airline = airline_performance_ranking.iloc[0]

worst_arrival_airline = airline_performance_ranking.iloc[-1]

best_arrival_airline, worst_arrival_airline

(AIRLINE              Endeavor Air Inc.
 TOTAL_FLIGHTS                   112463
 AVERAGE_DEP_DELAY             5.951135
 AVERAGE_ARR_DELAY            -1.258539
 CANCELLED_FLIGHTS               2394.0
 DIVERTED_FLIGHTS                 221.0
 CANCELLATION_RATE               2.1287
 DIVERSION_RATE                0.196509
 Name: 0, dtype: object,
 AIRLINE              Allegiant Air
 TOTAL_FLIGHTS                52738
 AVERAGE_DEP_DELAY        13.907797
 AVERAGE_ARR_DELAY        13.284601
 CANCELLED_FLIGHTS           2383.0
 DIVERTED_FLIGHTS             176.0
 CANCELLATION_RATE         4.518563
 DIVERSION_RATE            0.333725
 Name: 17, dtype: object)

## 2.13 Phase 2 Validation

The following Python concepts have now been applied to the actual
airline dataset:

- Lists
- Tuples
- Dictionaries
- for loops
- Conditional logic
- max()
- min()
- sorted()
- lambda functions
- DataFrame creation
- Group-level calculations
- Business KPI calculations

The next phase will move into Core Python concepts including
functions, modules, exception handling, and file handling.

In [27]:
# Confirm the main Phase 2 analytical objects

phase_2_objects = [
    "airlines",
    "airline_flight_counts",
    "airline_flight_dict",
    "airline_analysis",
    "airline_summary"
]

phase_2_objects

['airlines',
 'airline_flight_counts',
 'airline_flight_dict',
 'airline_analysis',
 'airline_summary']

# Phase 3 — Core Python

In this phase, we will apply Core Python concepts to the Airline Flight Delay Analysis project.

Topics covered:
- Tuples
- Dictionaries
- Sets
- Functions
- Modules
- Object-Oriented Programming (OOP)
- Exception Handling
- File Handling

The purpose is to build reusable and structured analytical logic before moving into NumPy and advanced Pandas analysis.

## 3.1 Tuples

A tuple is an ordered and immutable collection of values.

In this project, tuples can be used to store fixed business dimensions such as the columns required for an airline performance analysis.

Unlike a list, tuple values cannot be modified after creation.

In [28]:
airline_kpi_columns = (
    "AIRLINE",
    "TOTAL_FLIGHTS",
    "AVERAGE_DEP_DELAY",
    "AVERAGE_ARR_DELAY",
    "CANCELLED_FLIGHTS",
    "DIVERTED_FLIGHTS"
)

airline_kpi_columns

('AIRLINE',
 'TOTAL_FLIGHTS',
 'AVERAGE_DEP_DELAY',
 'AVERAGE_ARR_DELAY',
 'CANCELLED_FLIGHTS',
 'DIVERTED_FLIGHTS')

In [29]:
type(airline_kpi_columns)

tuple

In [30]:
airline_kpi_columns[0], airline_kpi_columns[-1]

('AIRLINE', 'DIVERTED_FLIGHTS')

## 3.2 Dictionaries

A dictionary stores data in key-value pairs.

Dictionaries are useful for representing business rules and configurations because each value can be accessed using a meaningful key.

In [31]:
delay_thresholds = {
    "ON_TIME": 15,
    "MODERATE_DELAY": 30,
    "HIGH_DELAY": 60
}

delay_thresholds

{'ON_TIME': 15, 'MODERATE_DELAY': 30, 'HIGH_DELAY': 60}

In [32]:
delay_thresholds["HIGH_DELAY"]

60

### Business Rule

For this project:

- Delay up to 15 minutes → On Time / Minor Delay
- Delay above 15 and up to 30 minutes → Moderate Delay
- Delay above 30 and up to 60 minutes → Significant Delay
- Delay above 60 minutes → Severe Delay

These are transparent business rules, not machine-learning predictions.

In [33]:
airline_project_config = {
    "delay_rules": delay_thresholds,
    "kpi_columns": airline_kpi_columns,
    "analysis_type": "Operational Performance Analysis"
}

airline_project_config

{'delay_rules': {'ON_TIME': 15, 'MODERATE_DELAY': 30, 'HIGH_DELAY': 60},
 'kpi_columns': ('AIRLINE',
  'TOTAL_FLIGHTS',
  'AVERAGE_DEP_DELAY',
  'AVERAGE_ARR_DELAY',
  'CANCELLED_FLIGHTS',
  'DIVERTED_FLIGHTS'),
 'analysis_type': 'Operational Performance Analysis'}

In [34]:
airline_project_config["delay_rules"]["MODERATE_DELAY"]

30

## 3.3 Sets

A set stores unique values.

Sets are useful in this project when we need to identify the number of unique airlines, airports, routes, or other categorical business entities.

In [35]:
unique_airlines_set = set(df["AIRLINE"].dropna())

len(unique_airlines_set)

18

In [36]:
unique_airlines_set

{'Alaska Airlines Inc.',
 'Allegiant Air',
 'American Airlines Inc.',
 'Delta Air Lines Inc.',
 'Endeavor Air Inc.',
 'Envoy Air',
 'ExpressJet Airlines LLC d/b/a aha!',
 'Frontier Airlines Inc.',
 'Hawaiian Airlines Inc.',
 'Horizon Air',
 'JetBlue Airways',
 'Mesa Airlines Inc.',
 'PSA Airlines Inc.',
 'Republic Airline',
 'SkyWest Airlines Inc.',
 'Southwest Airlines Co.',
 'Spirit Air Lines',
 'United Air Lines Inc.'}

In [37]:
unique_origins_set = set(df["ORIGIN"].dropna())
unique_destinations_set = set(df["DEST"].dropna())

len(unique_origins_set), len(unique_destinations_set)

(380, 380)

## 3.4 Functions

Functions allow us to package reusable logic into a single block of code.

Instead of repeatedly writing the same calculation, we can create a function and call it whenever required.

In this project, functions will be used to create reusable airline-level performance calculations.

In [38]:
def calculate_delay_rate(data, delay_column="ARR_DELAY", threshold=30):
    delayed_flights = (data[delay_column] > threshold).sum()
    total_flights = data[delay_column].notna().sum()
    
    if total_flights == 0:
        return 0
    
    return (delayed_flights / total_flights) * 100
calculate_delay_rate(df)

np.float64(11.362165308418348)

In [39]:
def airline_delay_rate(data, airline_name, threshold=30):
    airline_data = data[data["AIRLINE"] == airline_name]
    
    return calculate_delay_rate(
        airline_data,
        delay_column="ARR_DELAY",
        threshold=threshold
    )

airline_delay_rate(df, "Delta Air Lines Inc.")

np.float64(8.634789883518888)

## 3.5 Reusable Airline Performance Function

We will create a reusable function that calculates the main operational KPIs for any airline.

This reduces repeated code and makes the analysis easier to maintain.

In [40]:
def calculate_airline_metrics(data, airline_name):
    airline_data = data[data["AIRLINE"] == airline_name]
    
    total_flights = len(airline_data)
    
    metrics = {
        "AIRLINE": airline_name,
        "TOTAL_FLIGHTS": total_flights,
        "AVERAGE_DEP_DELAY": airline_data["DEP_DELAY"].mean(),
        "AVERAGE_ARR_DELAY": airline_data["ARR_DELAY"].mean(),
        "CANCELLED_FLIGHTS": airline_data["CANCELLED"].sum(),
        "DIVERTED_FLIGHTS": airline_data["DIVERTED"].sum(),
        "ARR_DELAY_OVER_30_RATE": calculate_delay_rate(
            airline_data,
            "ARR_DELAY",
            30
        )
    }
    
    return metrics
    
calculate_airline_metrics(df, "Southwest Airlines Co.")

{'AIRLINE': 'Southwest Airlines Co.',
 'TOTAL_FLIGHTS': 576470,
 'AVERAGE_DEP_DELAY': np.float64(10.81695730607336),
 'AVERAGE_ARR_DELAY': np.float64(3.2697955813330117),
 'CANCELLED_FLIGHTS': np.float64(19465.0),
 'DIVERTED_FLIGHTS': np.float64(1136.0),
 'ARR_DELAY_OVER_30_RATE': np.float64(10.9698508101729)}

### Applying the Function to All Airlines

The function can now be reused for every airline in the dataset.

In [41]:
airline_metrics_from_function = []

for airline in airlines:
    airline_metrics_from_function.append(
        calculate_airline_metrics(df, airline)
    )

airline_metrics_from_function

[{'AIRLINE': 'United Air Lines Inc.',
  'TOTAL_FLIGHTS': 254504,
  'AVERAGE_DEP_DELAY': np.float64(11.217032073646134),
  'AVERAGE_ARR_DELAY': np.float64(5.035985016312885),
  'CANCELLED_FLIGHTS': np.float64(5536.0),
  'DIVERTED_FLIGHTS': np.float64(698.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(12.258428324002095)},
 {'AIRLINE': 'Delta Air Lines Inc.',
  'TOTAL_FLIGHTS': 395239,
  'AVERAGE_DEP_DELAY': np.float64(8.106747590146377),
  'AVERAGE_ARR_DELAY': np.float64(1.0850788339017954),
  'CANCELLED_FLIGHTS': np.float64(5982.0),
  'DIVERTED_FLIGHTS': np.float64(782.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(8.634789883518888)},
 {'AIRLINE': 'Spirit Air Lines',
  'TOTAL_FLIGHTS': 95711,
  'AVERAGE_DEP_DELAY': np.float64(12.981880063789026),
  'AVERAGE_ARR_DELAY': np.float64(8.029484978540772),
  'CANCELLED_FLIGHTS': np.float64(2312.0),
  'DIVERTED_FLIGHTS': np.float64(199.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(14.34334763948498)},
 {'AIRLINE': 'Southwest Airlines Co.',
  'TOTAL_FLIGHTS': 576470,
  'AVERAGE_DEP_DELAY': np.float64(10.81695730607336),
  'AVERAGE_ARR_DELAY': np.float64(3.2697955813330117),
  'CANCELLED_FLIGHTS': np.float64(19465.0),
  'DIVERTED_FLIGHTS': np.float64(1136.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(10.9698508101729)},
 {'AIRLINE': 'American Airlines Inc.',
  'TOTAL_FLIGHTS': 383106,
  'AVERAGE_DEP_DELAY': np.float64(12.609895258577868),
  'AVERAGE_ARR_DELAY': np.float64(6.661228711969786),
  'CANCELLED_FLIGHTS': np.float64(10907.0),
  'DIVERTED_FLIGHTS': np.float64(981.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(12.727292318799197)},
 {'AIRLINE': 'Republic Airline',
  'TOTAL_FLIGHTS': 143107,
  'AVERAGE_DEP_DELAY': np.float64(5.8043589614099895),
  'AVERAGE_ARR_DELAY': np.float64(0.5901756824252427),
  'CANCELLED_FLIGHTS': np.float64(4646.0),
  'DIVERTED_FLIGHTS': np.float64(313.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(10.095767551955525)},
 {'AIRLINE': 'Alaska Airlines Inc.',
  'TOTAL_FLIGHTS': 100467,
  'AVERAGE_DEP_DELAY': np.float64(4.640017847002515),
  'AVERAGE_ARR_DELAY': np.float64(1.0979001770199606),
  'CANCELLED_FLIGHTS': np.float64(1934.0),
  'DIVERTED_FLIGHTS': np.float64(239.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(9.619101878039352)},
 {'AIRLINE': 'JetBlue Airways',
  'TOTAL_FLIGHTS': 112844,
  'AVERAGE_DEP_DELAY': np.float64(18.322555104566717),
  'AVERAGE_ARR_DELAY': np.float64(12.276124516889453),
  'CANCELLED_FLIGHTS': np.float64(3039.0),
  'DIVERTED_FLIGHTS': np.float64(358.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(18.842910267069907)},
 {'AIRLINE': 'PSA Airlines Inc.',
  'TOTAL_FLIGHTS': 107050,
  'AVERAGE_DEP_DELAY': np.float64(7.972124328384077),
  'AVERAGE_ARR_DELAY': np.float64(3.9286549481557356),
  'CANCELLED_FLIGHTS': np.float64(3301.0),
  'DIVERTED_FLIGHTS': np.float64(266.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(10.786312727694405)},
 {'AIRLINE': 'Allegiant Air',
  'TOTAL_FLIGHTS': 52738,
  'AVERAGE_DEP_DELAY': np.float64(13.907796771695754),
  'AVERAGE_ARR_DELAY': np.float64(13.284601127961896),
  'CANCELLED_FLIGHTS': np.float64(2383.0),
  'DIVERTED_FLIGHTS': np.float64(176.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(16.771956396101956)},
 {'AIRLINE': 'ExpressJet Airlines LLC d/b/a aha!',
  'TOTAL_FLIGHTS': 19082,
  'AVERAGE_DEP_DELAY': np.float64(12.774461948080763),
  'AVERAGE_ARR_DELAY': np.float64(10.03197593448833),
  'CANCELLED_FLIGHTS': np.float64(1062.0),
  'DIVERTED_FLIGHTS': np.float64(69.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(14.751267338866917)},
 {'AIRLINE': 'SkyWest Airlines Inc.',
  'TOTAL_FLIGHTS': 343737,
  'AVERAGE_DEP_DELAY': np.float64(9.458294288612626),
  'AVERAGE_ARR_DELAY': np.float64(4.023311421969874),
  'CANCELLED_FLIGHTS': np.float64(7745.0),
  'DIVERTED_FLIGHTS': np.float64(1006.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(10.287295588472354)},
 {'AIRLINE': 'Endeavor Air Inc.',
  'TOTAL_FLIGHTS': 112463,
  'AVERAGE_DEP_DELAY': np.float64(5.951134919193754),
  'AVERAGE_ARR_DELAY': np.float64(-1.2585390721724565),
  'CANCELLED_FLIGHTS': np.float64(2394.0),
  'DIVERTED_FLIGHTS': np.float64(221.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(8.660148568931616)},
 {'AIRLINE': 'Envoy Air',
  'TOTAL_FLIGHTS': 121256,
  'AVERAGE_DEP_DELAY': np.float64(6.728256254352146),
  'AVERAGE_ARR_DELAY': np.float64(3.2789143480632843),
  'CANCELLED_FLIGHTS': np.float64(3633.0),
  'DIVERTED_FLIGHTS': np.float64(311.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(10.39279869067103)},
 {'AIRLINE': 'Frontier Airlines Inc.',
  'TOTAL_FLIGHTS': 64466,
  'AVERAGE_DEP_DELAY': np.float64(16.03357413359641),
  'AVERAGE_ARR_DELAY': np.float64(11.100428951858525),
  'CANCELLED_FLIGHTS': np.float64(1666.0),
  'DIVERTED_FLIGHTS': np.float64(88.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(18.111655052542616)},
 {'AIRLINE': 'Mesa Airlines Inc.',
  'TOTAL_FLIGHTS': 65012,
  'AVERAGE_DEP_DELAY': np.float64(12.277382509651277),
  'AVERAGE_ARR_DELAY': np.float64(7.3098100100837105),
  'CANCELLED_FLIGHTS': np.float64(2373.0),
  'DIVERTED_FLIGHTS': np.float64(162.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(12.639851465339245)},
 {'AIRLINE': 'Horizon Air',
  'TOTAL_FLIGHTS': 20634,
  'AVERAGE_DEP_DELAY': np.float64(4.832774600670479),
  'AVERAGE_ARR_DELAY': np.float64(2.3762415377773385),
  'CANCELLED_FLIGHTS': np.float64(374.0),
  'DIVERTED_FLIGHTS': np.float64(23.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(7.767949794930079)},
 {'AIRLINE': 'Hawaiian Airlines Inc.',
  'TOTAL_FLIGHTS': 32114,
  'AVERAGE_DEP_DELAY': np.float64(5.089536716041601),
  'AVERAGE_ARR_DELAY': np.float64(3.8947567669884537),
  'CANCELLED_FLIGHTS': np.float64(388.0),
  'DIVERTED_FLIGHTS': np.float64(28.0),
  'ARR_DELAY_OVER_30_RATE': np.float64(7.120323048772794)}]

## 3.6 Modules

A module is a Python file containing reusable Python code.

Python provides many built-in modules.

For this project, we will use standard-library modules where they add practical value.

In [42]:
import math
import statistics

In [43]:
math.ceil(4.2), math.floor(4.8)

(5, 4)

In [44]:
sample_delay_values = [10, 20, 30, 40, 50]

statistics.mean(sample_delay_values)

30

## 3.7 Object-Oriented Programming (OOP)

Object-Oriented Programming organizes data and related operations inside classes and objects.

For this project, we will create a simple AirlinePerformanceAnalyzer class.

The class will store the dataset and provide methods for airline-level analysis.

In [45]:
class AirlinePerformanceAnalyzer:
    
    def __init__(self, data):
        self.data = data
    
    def airline_data(self, airline_name):
        return self.data[self.data["AIRLINE"] == airline_name]
    
    def average_arrival_delay(self, airline_name):
        airline_data = self.airline_data(airline_name)
        return airline_data["ARR_DELAY"].mean()
    
    def cancellation_rate(self, airline_name):
        airline_data = self.airline_data(airline_name)
        
        total_flights = len(airline_data)
        
        if total_flights == 0:
            return 0
        
        return (airline_data["CANCELLED"].sum() / total_flights) * 100

In [46]:
analyzer = AirlinePerformanceAnalyzer(df)

analyzer

In [47]:
analyzer.average_arrival_delay("Delta Air Lines Inc.")

np.float64(1.0850788339017954)

In [48]:
analyzer.cancellation_rate("Delta Air Lines Inc.")

np.float64(1.5135146076171633)

## 3.8 Exception Handling

Exception handling prevents the program from failing unexpectedly when an error occurs.

In data analytics, exception handling is useful when:
- a required column is missing
- a file cannot be loaded
- invalid input is supplied
- a calculation cannot be performed

In [49]:
def safe_airline_delay(data, airline_name):
    try:
        if "AIRLINE" not in data.columns:
            raise KeyError("AIRLINE column is missing")
        
        if "ARR_DELAY" not in data.columns:
            raise KeyError("ARR_DELAY column is missing")
        
        airline_data = data[data["AIRLINE"] == airline_name]
        
        if airline_data.empty:
            return None
        
        return airline_data["ARR_DELAY"].mean()
    
    except KeyError as error:
        return str(error)

In [50]:
safe_airline_delay(df, "Delta Air Lines Inc.")

np.float64(1.0850788339017954)

In [51]:
safe_airline_delay(df, "Unknown Airline")

## 3.9 File Handling

File handling allows Python to create, read, and write external files.

In this project, we will create a small text-based project configuration file.

The large raw dataset itself will continue to be handled through Pandas.

In [52]:
project_notes = """
Airline Flight Delay Analysis
Project Type: Business Analytics
Dataset Rows: 3,000,000
Main Objective: Analyze airline and operational flight delays
Machine Learning: Not used
"""

with open("project_notes.txt", "w", encoding="utf-8") as file:
    file.write(project_notes)

"project_notes.txt created"

'project_notes.txt created'

In [53]:
with open("project_notes.txt", "r", encoding="utf-8") as file:
    notes = file.read()

notes

'\nAirline Flight Delay Analysis\nProject Type: Business Analytics\nDataset Rows: 3,000,000\nMain Objective: Analyze airline and operational flight delays\nMachine Learning: Not used\n'

# Phase 3 Validation

Core Python topics completed:

- Tuple
- Dictionary
- Nested dictionary
- Set
- Functions
- Reusable analytical functions
- Modules
- Object-Oriented Programming
- Exception handling
- File handling

These concepts were demonstrated using the Airline Flight Delay Analysis project.

In [54]:
phase_3_topics = {
    "Tuple": True,
    "Dictionary": True,
    "Set": True,
    "Functions": True,
    "Modules": True,
    "OOP": True,
    "Exception Handling": True,
    "File Handling": True
}

phase_3_topics

{'Tuple': True,
 'Dictionary': True,
 'Set': True,
 'Functions': True,
 'Modules': True,
 'OOP': True,
 'Exception Handling': True,
 'File Handling': True}

# Phase 4 — NumPy

NumPy is a Python library used for numerical computing.

In this phase, we will use NumPy with the Airline Flight Delay dataset to perform:

- Array creation
- Array inspection
- Array operations
- Mathematical calculations
- Statistical calculations
- Conditional numerical analysis

NumPy will be used mainly for numerical calculations, while Pandas will continue to handle the tabular DataFrame structure.

## 4.1 Import NumPy

NumPy was already imported earlier in the project.

We will verify the NumPy version and continue using the existing `np` alias.

In [55]:
np.__version__

'2.5.0'

## 4.2 Creating NumPy Arrays

We can extract a numerical column from the actual airline dataset and convert it into a NumPy array.

We will use `ARR_DELAY` because arrival delay is one of the main business metrics in this project.

In [56]:
arrival_delay_array = df["ARR_DELAY"].dropna().to_numpy()

arrival_delay_array

array([-14.,  -5.,   0., ...,  36., -16., -10.], shape=(2913802,))

In [57]:
type(arrival_delay_array), arrival_delay_array.shape

(numpy.ndarray, (2913802,))

## 4.3 NumPy Array Properties

NumPy arrays provide useful properties such as:

- Number of dimensions
- Shape
- Number of elements
- Data type

These properties help us understand the numerical structure of the data.

In [58]:
arrival_delay_array.ndim

1

In [59]:
arrival_delay_array.size

2913802

In [60]:
arrival_delay_array.dtype

dtype('float64')

## 4.4 NumPy Mathematical Operations

NumPy allows mathematical operations to be applied efficiently to an entire array.

We will calculate basic transformations using the actual arrival-delay values.

In [61]:
delay_absolute = np.abs(arrival_delay_array)

delay_absolute[:10]

array([ 14.,   5.,   0.,  24.,   1., 141.,  29.,  23.,  11.,   1.])

In [62]:
delay_squared = np.square(arrival_delay_array)

delay_squared[:10]

array([1.9600e+02, 2.5000e+01, 0.0000e+00, 5.7600e+02, 1.0000e+00,
       1.9881e+04, 8.4100e+02, 5.2900e+02, 1.2100e+02, 1.0000e+00])

## 4.5 NumPy Statistical Operations

NumPy provides statistical functions such as:

- Mean
- Median
- Minimum
- Maximum
- Standard deviation
- Percentiles

These will help us understand the distribution of flight delays.

In [63]:
np.mean(arrival_delay_array)

np.float64(4.260858150279257)

In [64]:
np.median(arrival_delay_array)

np.float64(-7.0)

In [65]:
np.min(arrival_delay_array), np.max(arrival_delay_array)

(np.float64(-96.0), np.float64(2934.0))

## 4.6 Standard Deviation

Standard deviation measures how widely values are spread around the mean.

A higher standard deviation means flight arrival delays vary more widely.

This is useful for understanding operational consistency.

In [66]:
np.std(arrival_delay_array)

np.float64(51.174815579143115)

## 4.7 Delay Percentiles

Percentiles help us understand how delays behave across the dataset.

For example:

- 50th percentile → median
- 75th percentile → 75% of observations are below this value
- 90th percentile → 90% are below this value
- 95th percentile → extreme-delay threshold indicator

In [67]:
delay_percentiles = np.percentile(
    arrival_delay_array,
    [50, 75, 90, 95, 99]
)

delay_percentiles

array([ -7.,   7.,  36.,  71., 189.])

### Business Interpretation

Delay percentiles provide more information than average delay alone.

For example, the 95th percentile can help identify a high-delay operational threshold.

This can later support:
- Delay severity classification
- Airport risk analysis
- Route risk analysis
- Operational performance comparison

## 4.8 Conditional Numerical Analysis

NumPy can apply conditions to large numerical arrays efficiently.

We will identify flights with arrival delays greater than 30 minutes.

This threshold will later be used as one of the project's business rules.

In [68]:
delayed_over_30 = arrival_delay_array > 30

delayed_over_30[:20]

array([False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False])

In [69]:
delayed_over_30_count = np.sum(delayed_over_30)

delayed_over_30_count

np.int64(331071)

In [70]:
delayed_over_30_rate = (
    delayed_over_30_count /
    arrival_delay_array.size
) * 100

delayed_over_30_rate

np.float64(11.362165308418348)

## 4.9 Multiple Conditions

We can combine multiple numerical conditions using NumPy.

For this project, a severe arrival delay will be defined as a delay greater than 60 minutes.

In [71]:
severe_delay = arrival_delay_array > 60

severe_delay_count = np.sum(severe_delay)

severe_delay_count

np.int64(175135)

In [72]:
moderate_delay = (arrival_delay_array > 30) & (arrival_delay_array <= 60)

moderate_delay_count = np.sum(moderate_delay)

moderate_delay_count

np.int64(155936)

## 4.10 Rule-Based Delay Severity Classification

We will use `np.where()` to classify flights based on arrival delay.

Rules:

- Delay <= 15 minutes → ON_TIME
- Delay > 15 and <= 30 → MODERATE_DELAY
- Delay > 30 and <= 60 → SIGNIFICANT_DELAY
- Delay > 60 → SEVERE_DELAY

This is a transparent business-rule algorithm, not machine learning.

In [73]:
delay_severity = np.where(
    arrival_delay_array <= 15,
    "ON_TIME",
    np.where(
        arrival_delay_array <= 30,
        "MODERATE_DELAY",
        np.where(
            arrival_delay_array <= 60,
            "SIGNIFICANT_DELAY",
            "SEVERE_DELAY"
        )
    )
)

delay_severity[:20]

array(['ON_TIME', 'ON_TIME', 'ON_TIME', 'MODERATE_DELAY', 'ON_TIME',
       'SEVERE_DELAY', 'ON_TIME', 'MODERATE_DELAY', 'ON_TIME', 'ON_TIME',
       'SIGNIFICANT_DELAY', 'ON_TIME', 'ON_TIME', 'ON_TIME', 'ON_TIME',
       'ON_TIME', 'ON_TIME', 'ON_TIME', 'SIGNIFICANT_DELAY', 'ON_TIME'],
      dtype='<U17')

In [74]:
severity_labels, severity_counts = np.unique(
    delay_severity,
    return_counts=True
)

severity_summary = dict(
    zip(severity_labels, severity_counts)
)

severity_summary

{np.str_('MODERATE_DELAY'): np.int64(184218),
 np.str_('ON_TIME'): np.int64(2398513),
 np.str_('SEVERE_DELAY'): np.int64(175135),
 np.str_('SIGNIFICANT_DELAY'): np.int64(155936)}

## 4.11 Unique Numerical Categories

`np.unique()` can identify unique values and, when requested, their frequencies.

This is useful for validating categorical results created from numerical business rules.

In [75]:
np.unique(delay_severity)

array(['MODERATE_DELAY', 'ON_TIME', 'SEVERE_DELAY', 'SIGNIFICANT_DELAY'],
      dtype='<U17')

## 4.12 Validation

NumPy topics completed:

- NumPy array creation
- Array properties
- Mathematical operations
- Mean
- Median
- Minimum
- Maximum
- Standard deviation
- Percentiles
- Conditional operations
- Boolean arrays
- Counting conditions
- Multiple conditions
- `np.where()`
- `np.unique()`
- Rule-based numerical classification

All numerical analysis was performed using the actual Airline Flight Delay dataset.

In [76]:
phase_4_topics = {
    "Array Creation": True,
    "Array Properties": True,
    "Mathematical Operations": True,
    "Mean": True,
    "Median": True,
    "Minimum": True,
    "Maximum": True,
    "Standard Deviation": True,
    "Percentiles": True,
    "Conditional Operations": True,
    "Boolean Arrays": True,
    "np.where": True,
    "np.unique": True
}

phase_4_topics

{'Array Creation': True,
 'Array Properties': True,
 'Mathematical Operations': True,
 'Mean': True,
 'Median': True,
 'Minimum': True,
 'Maximum': True,
 'Standard Deviation': True,
 'Percentiles': True,
 'Conditional Operations': True,
 'Boolean Arrays': True,
 'np.where': True,
 'np.unique': True}